include $(THEOS)/makefiles/common.mk
ARCHS = arm64 arm64e
TOOL_NAME = mk1

mk1_FILES = main.m
mk1_CFLAGS = -fobjc-arc
mk1_LIBRARIES = rocketbootstrap
mk1_PRIVATE_FRAMEWORKS = AppSupport

include $(THEOS_MAKE_PATH)/tool.mk
